Repository BuildingSync/schema, pull requests merged in 2020-07, with the labels that each got.

#202 feat/add OriginalOccupancyClassification element to Section
  BuildingSync.xsd
Labels: DO NOT MERGE

#209 Update annotations for consistency
  .gitignore
  BuildingSync.xsd
  Rakefile
Labels: General, Non-breaking Change

#211 Release 2.1
  .gitignore
  BuildingSync.xsd
  CHANGELOG.md
  Gemfile
  Rakefile
  docs/DataDictionary.xlsx
  docs/enumerations.json
  docs/release_instructions.md
  examples/ASHRAE 211 Export.xml
  examples/AT_BRICR_audit_report.xml
  examples/AT_example_NYC_audit_report_property.xml
  examples/AT_example_SF_audit_report.xml
  examples/AT_example_property_report_25.xml
  examples/AT_example_report_332.xml
  examples/BuildingSync Website Invalid Schema.xml
  examples/BuildingSync Website Valid Schema.xml
  examples/CMS Woodlawn Campus.xml
  examples/DC GSA Headquarters.xml
  examples/Golden Test File.xml
  examples/LL87.xml
  examples/Multi-Facility Shared Systems.xml
  examples/MultitenantBySubsections.xml
  examples/NIST Gaithersburg Campus.xml
  examples/Norfolk Federal Building.xml
  examples/Reference Building - Primary School.xml
  examples/Richmond Federal Building.xml
  proposals/2020/Add Canadian Provinces to States.md
  proposals/2020/Add Energy Cost Index.md
  src/change_log.rb
  src/data_dictionary.rb
Labels: ignore
