Repository BuildingSync/schema, pull requests merged in 2021-12, with the labels that each got.

#424 Add Implement hot aisle cold aisle design
  BuildingSync.xsd
  proposals/2021/Fix Implement hot aisle cold aisle design.md
Labels: bug, Schema: Measures, Non-breaking Change

#425 Deprecate Implement hot aisle hold aisle design
  BuildingSync.xsd
  proposals/2021/Deprecte Implement hot aisle hold aisle design.md
Labels: bug, Schema: Measures, Breaking Change

#421 refactor: allow versions without PATCH included
  BuildingSync.xsd
Labels: Schema: General, Non-breaking Change

#423 Rename reference element
  BuildingSync.xsd
  examples/ASHRAE 211 Export.xml
  examples/AT_example_NYC_audit_report_property.xml
  examples/AT_example_SF_audit_report.xml
  examples/BuildingSync Website Invalid Schema.xml
  examples/BuildingSync Website Valid Schema.xml
  examples/Golden Test File.xml
  examples/LL87.xml
  examples/Multi-Facility Shared Systems.xml
  examples/Multi_building_gbxml_externalreference_geometry.xml
  examples/Reference Building - Primary School.xml
  examples/Single_building_gbxml_externalreference_geometry.xml
  proposals/2021/Rename reference elements.md
  spec/data/v2_for_translation.xml
  spec/data/v3_for_translation.xml
  spec/validation_spec.rb
  translation/v2_to_v3.xsl
  translation/v3_to_v2.xsl
  translation/xsltproc.py
Labels: enhancement, Schema: Measures, Schema: Reports, Schema: General, Schema: Systems, Breaking Change

#426 Update example version reference to 2.4
  examples/ASHRAE 211 Export.xml
  examples/AT_example_AS_conversion_audit_report.xml
  examples/AT_example_NYC_audit_report_property.xml
  examples/AT_example_SF_audit_report.xml
  examples/BuildingSync Website Invalid Schema.xml
  examples/BuildingSync Website Valid Schema.xml
  examples/CMS Woodlawn Campus.xml
  examples/DC GSA Headquarters.xml
  examples/Golden Test File.xml
  examples/LL87.xml
  examples/Multi-Facility Shared Systems.xml
  examples/Multi_building_gbxml_externalreference_geometry.xml
  examples/MultitenantBySubsections.xml
  examples/NIST Gaithersburg Campus.xml
  examples/Norfolk Federal Building.xml
  examples/Reference Building - Primary School.xml
  examples/Richmond Federal Building.xml
  examples/Single_building_gbxml_externalreference_geometry.xml
Labels: No Schema Changes

#422 Proposals for DC BEPS template
  proposals/2021/Add ACH75 and ACH100 to AirInfiltrationValueUnits.md
  proposals/2021/Add AirInfiltrationTestPressureBoundary.md
  proposals/2021/Add AirInfiltrationTestPressureDifferential.md
  proposals/2021/Add AirSideEconomizerCondition.md
  proposals/2021/Add Podium.md
  proposals/2021/Add Unitized.md
  proposals/2021/Add YearInstalled to FenestrationSystemType.md
Labels: Schema: General, Non-breaking Change, feature, No Schema Changes
