Repository BuildingSync/schema, pull requests merged in 2021-05, with the labels that each got.

#299 Proposals/section spatial units
  BuildingSync.xsd
  proposals/2021/Add SpatialUnits to Section.md
  spec/validation_spec.rb
Labels: Non-breaking Change, UDFs, feature

#335 Address issue using `/` with spaces
  BuildingSync.xsd
  proposals/2021/Break Insulate attic hatch stair box into two.md
  proposals/2021/Break Repair leaks seal ducts into two.md
Labels: Breaking Change, CTS-Support

#341 Refactor Measurename minOccurs maxOccurs
  .github/workflows/publish.yml
  BuildingSync.xsd
  docs/release_instructions.md
  docs/versioning.md
  proposals/2021/Add SpatialUnits to Section.md
  proposals/2021/Refactor MeasureName minOccurs maxOccurs.md
  spec/validation_spec.rb
Labels: Breaking Change

#344 docs: add notes for making pre-releases
  .github/workflows/publish.yml
  docs/release_instructions.md
Labels: Documentation

#342 Deprecate MORE in eGRIDRegionCode
  BuildingSync.xsd
  proposals/2021/Deprecate MORE in eGRIDRegionCode.md
Labels: Breaking Change, bug

#331 Remove redundant "Add or replace cooling tower"
  BuildingSync.xsd
  proposals/2021/Delete Add or replace cooling tower.md
Labels: Breaking Change

#329 Remove redundant items
  BuildingSync.xsd
  proposals/2021/Delete Add heat recovery.md
  proposals/2021/Delete Energy cost reduction through rate adjustments - uncategorized.md
  proposals/2021/Delete FutureOtherECMs.md
  proposals/2021/Delete Install or Upgrade Master Venting.md
  proposals/2021/Delete Separate SHW from heating.md
Labels: Breaking Change, CTS-Support

#334 Correct capitalization - change `Convert to Cleaner Fuels` to `Convert to cleaner fuels`
  BuildingSync.xsd
  proposals/2021/Change Cleaner Fuels to cleaner fuels.md
Labels: Breaking Change, CTS-Support

#348 Feat/translation
  .gitignore
  spec/data/v2_for_translation.xml
  spec/validation_spec.rb
  translation/README.md
  translation/v2_to_v3.xsl
  translator/css/agate.min.css
  translator/css/bootstrap.min.css
  translator/fonts/glyphicons-halflings-regular.eot
  translator/fonts/glyphicons-halflings-regular.svg
  translator/fonts/glyphicons-halflings-regular.ttf
  translator/fonts/glyphicons-halflings-regular.woff
  translator/fonts/glyphicons-halflings-regular.woff2
  translator/js/FileSaver.min.js
  translator/js/bootstrap.min.js
  translator/js/highlight.pack.js
  translator/js/jquery.min.js
  translator/js/jsonix-min.js
  translator/js/vkbeautify.min.js
  translator/mappings/1.0.js
  translator/mappings/2.0.js
  translator/translate.html
Labels: General, Non-breaking Change
