Repository BuildingSync/schema, pull requests merged in 2021-09, with the labels that each got.

#378 Feat/v3 to v2 translation
  BuildingSync.xsd
  spec/data/v3_for_translation.xml
  spec/validation_spec.rb
  translation/v2_to_v3.xsl
  translation/v3_to_v2.xsl
  translation/xsltproc.py
Labels: Non-breaking Change

#385 Add PRMS in eGRIDRegionCode for develop branch
  BuildingSync.xsd
  proposals/2021/Add PRMS.md
Labels: General, Non-breaking Change, feature

#382 Add PRMS in eGRIDRegionCode
  BuildingSync.xsd
  proposals/2021/Add PRMS.md
Labels: General, Non-breaking Change, feature

#392 Update change_log.rb
  src/change_log.rb
Labels: enhancement, Non-breaking Change

#394 Deprecate eGRIDRegionCode
  BuildingSync.xsd
  proposals/2021/Deprecate eGRIDRegionCode.md
  translation/v2_to_v3.xsl
Labels: General, Breaking Change

#395 Add MaximumOutsideAirFlowRate
  BuildingSync.xsd
  proposals/2021/Add MaximumOutsideAirFlowRate.md
Labels: Systems, Non-breaking Change, feature

#396 Deprecate MaximumOAFlowRate
  BuildingSync.xsd
  proposals/2021/Deprecate MaximumOAFlowRate.md
  spec/data/v2_for_translation.xml
  spec/data/v3_for_translation.xml
  translation/v2_to_v3.xsl
  translation/v3_to_v2.xsl
Labels: enhancement, Systems, Breaking Change

#398 Build/prep 2.4 release
  BuildingSync.xsd
  CHANGELOG.md
Labels: ignore
