Repository BuildingSync/schema, pull requests merged in 2022-03, with the labels that each got.

#435 Add example with sensor data in notebook directory
  .gitignore
  docs/notebooks/example1-with-sensors.xml
Labels: DO NOT MERGE, Non-breaking Change, Schema: Documentation

#436 Schema modifications for CO2e
  BuildingSync.xsd
  docs/notebooks/example1-with-sensors.xml
  proposals/2022/Add Emissions.md
Labels: Schema: Reports, Non-breaking Change

#439 Schema: Update notebook
  docs/notebooks/bsync_examples/Small-Office-Level-1.ipynb
Labels: Non-breaking Change, Schema: Documentation
