Repository BuildingSync/schema, pull requests merged in 2023-08, with the labels that each got.

#477 Add FacilityEvaluationAuditDefinition
  BuildingSync.xsd
  proposals/2023/Add FacilityEvaluationAuditDefinition.md
Labels: Schema: Reports, Non-breaking Change, feature

#480 Add WCM categories
  BuildingSync.xsd
  proposals/2023/Add WCM Categories.md
Labels: enhancement, Schema: Measures, Non-breaking Change, feature

#481 Add WCMs to existing categories
  BuildingSync.xsd
  proposals/2023/Add WCMs to existing Measure Categories.md
Labels: enhancement, Schema: Measures, Non-breaking Change, feature

#483 Make migrations scripts
  migration_scripts/README.md
  migration_scripts/upgrade_from_2.4_to_2.5.py
Labels: Non-breaking Change, Schema: No Changes
