Repository BuildingSync/schema, pull requests merged in 2023-01, with the labels that each got.

#458 Update Audit Template examples
  examples/AT_example_AS_conversion_audit_report.xml
  examples/AT_example_NYC_audit_report_property.xml
  examples/AT_example_SF_audit_report.xml
Labels: Non-breaking Change, Schema: No Changes

#462 run update on Python notebook dependencies
  docs/notebooks/README.md
  docs/notebooks/poetry.lock
Labels: Non-breaking Change, Schema: No Changes

#460 Proposal: Add RCx Auditor Qualification Types
  BuildingSync.xsd
  proposals/2022/Add RCx Auditor Qualification Types.md
Labels: Schema: General, Non-breaking Change

#453 Create Add Package-Measure Energy Savings Analyses.md
  BuildingSync.xsd
  examples/AT_example_AS_conversion_audit_report.xml
  proposals/2022/Add Package-Measure Energy Savings Analyses.md
Labels: Schema: Measures, Non-breaking Change
